# Generated by Django 5.2.4 on 2026-03-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
